name: "Test"
on:
  push:
jobs:
  lambda:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: cachix/install-nix-action@v22
    - name: Add static-haskell-nix cache
      uses: cachix/cachix-action@v12
      with:
        name: static-haskell-nix
    - name: Add umklappbot cache
      uses: cachix/cachix-action@v12
      with:
        name: umklappbot
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - run: nix-build -A function-zip
    - run: cp function/function.zip .
    - name: Deploy to Amazon Lambda
      if: github.ref == 'refs/heads/master'
      uses: appleboy/lambda-action@master
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: umklappbot
        zip_file: function.zip
        runtime: provided.al2

